# 부록: 통계 개념 및 방법 목록 (Appendix: Statistical Concepts and Methods)

색인을 보완하기 위해, 통계 개념 및 절차와 이들이 다루어진 장의 목록을 제공합니다.

**방법** | 장  
---|---  
분산분석 | [8 고처리량 카운트 데이터 & 일반화 선형 모델](08-chap.html)  
베이지안 통계 | [2 통계 모델링](02-chap.html)  
부트스트랩 | [4 혼합 모델](04-chap.html), [5 군집화](05-chap.html)  
카이제곱 검정 | [2 통계 모델링](02-chap.html)  
군집화 | [4 혼합 모델](04-chap.html), [5 군집화](05-chap.html)  
대응분석 | [9 이질적 데이터를 위한 다변량 방법](09-chap.html)  
데이터 변환 | [4 혼합 모델](04-chap.html), [8 고처리량 카운트 데이터 & 일반화 선형 모델](08-chap.html)  
확산 맵 모델 | [9 이질적 데이터를 위한 다변량 방법](09-chap.html)  
거리 | [4 혼합 모델](04-chap.html), [9 이질적 데이터를 위한 다변량 방법](09-chap.html)  
탐색적 데이터 분석 (EDA) | [3 데이터 시각화](03-chap.html)  
피셔의 정확 검정 | [10 네트워크와 트리](10-chap.html)  
거짓 발견율 (FDR) | [6 검정](06-chap.html)  
적합도 | [2 통계 모델링](02-chap.html)  
일반화 선형 모델 | [8 고처리량 카운트 데이터 & 일반화 선형 모델](08-chap.html)  
초기하 검정 | [10 네트워크와 트리](10-chap.html)  
가설 검정 | [1 이산 데이터를 위한 생성 모델](01-chap.html), [6 검정](06-chap.html)  
마르코프 체인 | [2 통계 모델링](02-chap.html), [10 네트워크와 트리](10-chap.html)  
최대 우도 | [2 통계 모델링](02-chap.html)  
다차원 척도법 (MDS) | [9 이질적 데이터를 위한 다변량 방법](09-chap.html)  
다중 가설 검정 | [6 검정](06-chap.html)  
다변량 회귀 | [8 고처리량 카운트 데이터 & 일반화 선형 모델](08-chap.html), [9 이질적 데이터를 위한 다변량 방법](09-chap.html), [12 지도 학습](12-chap.html)  
서열화 및 기울기 탐지 | [9 이질적 데이터를 위한 다변량 방법](09-chap.html)  
P-값 | [1 이산 데이터를 위한 생성 모델](01-chap.html)  
순열 검정 | [10 네트워크와 트리](10-chap.html)  
계통발생학 | [10 네트워크와 트리](10-chap.html)  
검정력 계산 | [13 고처리량 실험 설계 및 분석](13-chap.html)  
주성분 분석 (PCA) | [7 다변량 분석](07-chap.html)  
주좌표 분석 (PCoA) | [9 이질적 데이터를 위한 다변량 방법](09-chap.html)  
회귀 | [7 다변량 분석](07-chap.html),  
강건한 방법 | [12 지도 학습](12-chap.html)  
공간 통계 | [11 이미지 데이터](11-chap.html)  
  
페이지는 R 버전 4.5.1 (2025-06-13)을 사용하여 2025-09-01 01:33에 빌드되었습니다.

